# Generated by Django 2.2.11 on 2020-04-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovirtual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.TextField()),
                ('Preco', models.TextField()),
                ('PrecoArea', models.TextField()),
                ('Localizacao', models.TextField()),
                ('Propriedades', models.TextField()),
                ('Caracteristicas', models.TextField()),
                ('Imobiliaria', models.TextField()),
                ('Descricao', models.TextField()),
                ('Tipo', models.TextField()),
            ],
        ),
    ]
