# Generated by Django 2.2.11 on 2020-04-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovirtual',
            name='Alugar',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
